### ISSUE TITLE
Can you please help me figure out what's wrong

### ISSUE THREAD

**Issue by asaha1** [asaha1/x9115arn#2]
For code 2 I've followed the instructions to install Tkinter and Swampy. It's not printing any error msg while i write "import Tkinter" but on running the program it is showing this error.
![issue](https://cloud.githubusercontent.com/assets/13953290/9754186/b07bccee-5694-11e5-8bea-6e9a610cba89.png)

**Comment by timm** [comment]
what platform? cloud9?

matplotlib assumes it is talking to some x windows environment. which is not true for cloud9

please run the following code on cloud9, check that you get the **same** bug.

now uncomment the second line and check bug goes away. 

if it does that you need to add some combination of the first 3 lines to your code. get back to me on this asap since lots of folks will be having this issue

thanks!

t

`````` python
import matplotlib
#matplotlib.use('Agg') #<=== uncomment for second run
import matplotlib.pyplot as plt 

def lines(xlabel, ylabel, title, f="lines.png",
          xsize=5,ysize=5,lines=[]): 
  width = len(lines[0][1:])
  xs = [x for x in xrange(1,width+1)] 
  plt.figure(figsize=(xsize,ysize))
  plt.xlabel(xlabel)
  plt.ylabel(ylabel) 
  for line in lines: 
    plt.plot(xs,  line[1:],
                 label = line[0])

  plt.locator_params(nbins=len(xs))
  plt.title(title)
  plt.legend()
  plt.tight_layout()
  plt.savefig(f)

lines("days","production","Fruit output",
      xsize=3,ysize=3,lines=[
      ["apples",4,3,2,1],
      ["oranges",9,4,1,0.5]])```

``````

**Comment by asaha1** [comment]
I'm using Cloud9. Yes the bug goes away on doing so. But I can't figure out the 'combination'.

**Comment by timm** [comment]
so you can get my code to work but not yours?

can you come to my office 3pm?

**Comment by asaha1** [comment]
Dear Dr. M,
I have my TA hours ending at 4.30. I can come after that. Is that OK with
you?

**Comment by timm** [comment]
this bug has me worried. i'm actually free 2pm to 5. can i start working on this at 2pm? i cant see mypolygon.py in your repo. where is the crashing code that i can run?

t

**Comment by asaha1** [comment]
Dr M,
I've pushed the file into git. You will be able to see it now.
